<a href="https://colab.research.google.com/github/kevin-hyun/numpy-practice/blob/main/2_N%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%9D%B8%EB%8D%B1%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# N차원 배열의 인덱싱

## 1차원 배열


In [ ]:
import numpy as np 

In [ ]:
arr = np.arange(10)
print(arr)

print(arr[3])


[0 1 2 3 4 5 6 7 8 9]
3


## 2차원 배열

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr,arr.shape,arr.ndim)

print(arr[0,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
4


In [ ]:
arr = np.array([0,1,2,3,4,5,6])
print(arr[3:8])
print(arr[:-1])

[3 4 5 6]
[0 1 2 3 4 5]


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

## 0번째 행 + 모든 열

print(arr[0,:],"\n")

## 모든 열 + 2번째 값
print(arr[:,1],"\n")

# 행 1행~2행 ,  모든 열 

print(arr[:2,:],"\n")

# 행 1행~2행 , 2열~ 끝까지

print(arr[:2,2:],"\n")




[1 2 3 4] 

[ 2  6 10] 

[[1 2 3 4]
 [5 6 7 8]] 

[[3 4]
 [7 8]] 



## fancy indexing



In [ ]:
# 1차원 배열

arr = np.array([5,10,15,20,25,30])
print(arr[[0,2,4]])

[ 5 15 25]


In [ ]:
#2차원 배열
arr  = np.array([[5,10,15,20],[25,30,35,40],[45,50,55,60]])

## 0행, 2행의 값에 대해서 2열~ 끝까지
print(arr[[0,2],2:])

##  2행~끝까지, 3열, 4열의 값 
print(arr[1:,[2,3]])


[[15 20]
 [55 60]]
[[35 40]
 [55 60]]


## boolean indexing

In [ ]:
arr = np.array([1,2,3,4])
print(arr[[True,False,True,True]])



arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[[True,False],True])


## 조건 연산자
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr[arr>3])
print(arr[arr<=2])

[1 3 4]
[[1 2 3 4]]
[4 5 6 7 8]
[1 2]
