<a href="https://colab.research.google.com/github/kevin-hyun/numpy-practice/blob/main/3_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

# 배열의 연산


## 사칙연산/제곱/제곱근/제곱/몫/나머지

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[2,2,2],[2,2,2],[2,2,2]])


## plus

print(arr1+arr2, "\n")
print(np.add(arr1,arr2), "\n")




[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 



In [ ]:
# subtract
print(arr1-arr2, "\n")
print(np.subtract(arr1,arr2), "\n")



[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]] 

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]] 



In [ ]:
# mul

## 같은 자리의 원소끼리만 곱셉
print(arr1*arr2, "\n")
print(np.multiply(arr1,arr2), "\n")


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 



In [ ]:
# divide

print(arr1/arr2, "\n")
print(np.divide(arr1,arr2), "\n")

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]] 

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]] 



In [ ]:
# 제곱

print(arr1**2, "\n")
print(np.square(arr1), "\n")

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 



In [ ]:
# 제곱근

print(np.sqrt(arr1), "\n")

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]] 



In [ ]:
# 몫

print(arr1//2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [ ]:
# 나머지

print(arr1%2)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


## dot product/ 절댓값/올림/내림/반올림/버림

In [ ]:
#dot product- 

## 1차원 행렬

arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])

print(np.dot(arr1,arr2))
## 2*1, 3*2, 4*3

20


In [ ]:
## 2차원 행렬
## 행렬곱


arr1 = np.array([[1,2,],[3,4]])
arr2 = np.array([[1,2,],[0,3]])


print(np.dot(arr1,arr2))




[[ 1  8]
 [ 3 18]]


In [ ]:
# absolute

arr1 = np.array([[1,-2],[-4,5]])

print(np.abs(arr1))

[[1 2]
 [4 5]]


In [ ]:
# 올림

arr1 = np.array([[1.942,2.123],[1.112,2.9]])
print(np.ceil(arr1))


# 내림

print(np.floor(arr1))


# 반올림

print(np.round(arr1))


# 버림

print(np.trunc(arr1))


[[2. 3.]
 [2. 3.]]
[[1. 2.]
 [1. 2.]]
[[2. 2.]
 [1. 3.]]
[[1. 2.]
 [1. 2.]]


##  min / max / sum / mean/ sid / cumsum /median


In [ ]:
arr = np.array([[1,2,3],[0,1,4]])

In [ ]:
#  min 

print("min---")
print(np.min(arr))
print(arr.min())
print(arr.min(axis=0)) # 1/0. 2/1. 3/4 
print(arr.min(axis=1)) # 1/2/3. 0/1/4

print("----------")

# max
print("max---")
print(np.max(arr))
print(arr.max())
print(arr.max(axis=0)) # 1/0. 2/1. 3/4 
print(arr.max(axis=1)) # 1/2/3. 0/1/4
print("----------")
# sum

print("sum---")
print(np.sum(arr))
print(arr.max(axis=0)) # 1/0. 2/1. 3/4 
print(arr.max(axis=1)) # 1/2/3. 0/1/4
print("----------")
# mean

print("mean---")
print(np.mean(arr)) # 1/2/3/0/1/4
print(arr.mean(axis=0)) # 1/0. 2/1. 3/4 
print(arr.mean(axis=1)) # 1/2/3. 0/1/4
print("----------")

# std - 표준편차

print("std---")
print(np.std(arr))
print(arr.std(axis=0)) # 1/0. 2/1. 3/4 
print(arr.std(axis=1)) # 1/2/3. 0/1/4
print("----------")



# cumsum- 누적합
print("cumsum---")
print(np.cumsum(arr))
print(arr.cumsum(axis=0)) # 1/0. 2/1. 3/4 
print(arr.cumsum(axis=1)) # 1/2/3. 0/1/4
print("----------")



arr = np.array([[1,2,3],[0,1,4],[1,5,2]])


# median
print("median---")
print(np.median(arr))
print(np.median(arr,axis=0)) # 1/0. 2/1. 3/4 
print(np.median(arr,axis=1)) # 1/2/3. 0/1/4
print("----------")

min---
0
0
[0 1 3]
[1 0]
----------
max---
4
4
[1 2 4]
[3 4]
----------
sum---
11
[1 2 4]
[3 4]
----------
mean---
1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]
----------
std---
1.343709624716425
[0.5 0.5 0.5]
[0.81649658 1.69967317]
----------
cumsum---
[ 1  3  6  6  7 11]
[[1 2 3]
 [1 3 7]]
[[1 3 6]
 [0 1 5]]
----------
median---
2.0
[1. 2. 3.]
[2. 1. 2.]
----------


## 비교연산/ 삼각함수

In [ ]:
# 비교연산

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,0,3],[4,-2,9]])


## 
print(arr1 == arr2)

## large/less 

print(arr1>=arr2)


## 완전 동일 여부
print(np.array_equal(arr1,arr2))

[[ True False  True]
 [ True False False]]
[[ True  True  True]
 [ True  True False]]
False


In [ ]:
# 삼각함수
arr1 = np.array([[1,2,3],[4,5,6]])

# sin
print(np.sin(arr))

# cos
print(np.cos(arr))

# tan
print(np.tan(arr))

# pi

print(np.pi)

[[ 0.84147098  0.90929743  0.14112001]
 [ 0.          0.84147098 -0.7568025 ]
 [ 0.84147098 -0.95892427  0.90929743]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [ 1.          0.54030231 -0.65364362]
 [ 0.54030231  0.28366219 -0.41614684]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 0.          1.55740772  1.15782128]
 [ 1.55740772 -3.38051501 -2.18503986]]
3.141592653589793


# broadcastin -- shape 달라도 연산 가능 - 원소를 확장

In [ ]:
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
arr2 = np.array([[5,6,7]])

print(arr1 + arr2)

arr1 = np.array([[1,1,1]])
arr2 = np.array([[0],[1],[2]])


print(arr1 + arr2)



[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


```
arr1 = np.array([[1,1,1]])
arr2 = np.array([[0],[1],[2]])
```
[1,1,1] + [[0,0,0],[1,1,1],[2,2,2]]



## 백터 연산의 장점 
- 속도 빠르다

In [ ]:
import time

In [ ]:
arr = np.arange(0,100000)

In [ ]:
# for 
sum =0 
before = time.time()
for i in arr:
  sum +=1
after = time.time()

print(sum, after-before,"초")

1000000000 186.36407256126404 초


In [ ]:
# vector 

before = time.time()
sum = np.sum(arr)
after = time.time()

print(sum, after-before,"초")

1000000000 1.495948076248169 초


In [ ]:
arr1 = np.arange(10000000)
arr2 = np.arange(10000000)

sum = 0
before = time.time()
for i,j in zip(arr1,arr2):
  sum += 1*j
after = time.time()

print(sum, after-before,"초")


49999995000000 7.16740083694458 초


In [ ]:
# 벡터 


before = time.time()
sum = np.dot(arr1,arr2)
after = time.time()

print(sum, after-before,"초")

1291890006563070912 0.029404640197753906 초
