<a href="https://colab.research.google.com/github/kevin-hyun/numpy-practice/blob/main/4_n%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4_%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# n차원 배열 정렬

# 1차원 배열 정렬

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(10,size=10)
print(arr)

[9 3 0 2 5 8 4 8 6 6]


In [ ]:
## upscale
print(np.sort(arr))

[0 2 3 4 5 6 6 8 8 9]


In [ ]:
## downscale
print(np.sort(arr)[::-1]) ##shallow copy

[9 8 8 6 6 5 4 3 2 0]


In [ ]:
## 정렬 자료 유지- deep copy

arr.sort()

print(arr)

[0 2 3 4 5 6 6 8 8 9]


# 2차원 배열 정렬

In [ ]:
arr = np.random.randint(15,size=(3,4))
print(arr)

[[13  1  6 12]
 [13  5  6  2]
 [14 10  0  4]]


In [ ]:
## default  : axis = 1
print(np.sort(arr)) 


print(np.sort(arr,axis=0)) 

# 2차원 -> 1차원

print(np.sort(arr,axis=None))

[[ 1  6 12 13]
 [ 2  5  6 13]
 [ 0  4 10 14]]
[[13  1  0  2]
 [13  5  6  4]
 [14 10  6 12]]
[ 0  1  2  4  5  6  6 10 12 13 13 14]


In [ ]:
#argsort()

## - 정렬된 자료의 원본 배열(행)에서의 index표시 
print(arr)
print(np.sort(arr,axis=1))

print(np.argsort(arr,axis=1))

print("---------")

## - 정렬된 자료의 원본 배열(열)에서의 index표시 
print(arr)
print(np.sort(arr,axis=0))

print(np.argsort(arr,axis=0))


[[13  1  6 12]
 [13  5  6  2]
 [14 10  0  4]]
[[ 1  6 12 13]
 [ 2  5  6 13]
 [ 0  4 10 14]]
[[1 2 3 0]
 [3 1 2 0]
 [2 3 1 0]]
---------
[[13  1  6 12]
 [13  5  6  2]
 [14 10  0  4]]
[[13  1  0  2]
 [13  5  6  4]
 [14 10  6 12]]
[[0 0 2 1]
 [1 1 0 2]
 [2 2 1 0]]
