<a href="https://colab.research.google.com/github/kevin-hyun/numpy-practice/blob/main/5_n%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4_%ED%98%95%ED%83%9C_%EB%B3%80%EA%B2%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#n차원 배열 형태 변경

## reshape

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(12)
print(arr)
print("차원 : ", arr.ndim)

## reshape- 원본 변경 x 
# 원소의 개수는 맞아야 함- 안맞으면 err-- 개수만 맞으면 n 차원 가능 - 
arr = arr.reshape(3,4)
print(arr)

arr = arr.reshape(2,2,3)
print(arr)

# curse of dimensionality 
## 학습데이터 < 차원 --> 비효율 (데이터 사이 거리가 멀어짐)


## (n,-1) --> -1이 총 갯수/n 수로 변함

arr=np.arange(12)
arr = arr.reshape(3,-1) ### -1 -> 4
print(arr)

arr=np.arange(12)
arr = arr.reshape(6,-1)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
차원 :  1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


## resize, ravel

In [ ]:
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# resize - 원본 변경
arr.resize (3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# ravel-  1차원으로 

arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## expand_dims(), squeeze()

In [ ]:
#expand_dims()

arr= np.array([1,2])
print(arr,arr.shape)

arr = np.expand_dims(arr,axis=0)
print(arr,arr.shape)
    

    

[1 2] (2,)
[[1 2]] (1, 2)


In [ ]:
arr= np.array([1,2])
arr = np.expand_dims(arr,axis=1)
print(arr,arr.shape)


[[1]
 [2]] (2, 1)


In [ ]:
# squeeze()

arr = np.array([[1,2]])
print(arr,arr.shape,arr.ndim)

arr = np.squeeze(arr,axis=0)
print(arr,arr.shape,arr.ndim)

print("------")

arr = np.array([[[1],[2],[3]]])
print(arr,arr.shape,arr.ndim)
arr = np.squeeze(arr,axis=0)
print(arr,arr.shape,arr.ndim)

## axis 입력안하면 1차원으로 된다. 
print("------")
arr = np.squeeze(arr)
print(arr,arr.shape,arr.ndim)

[[1 2]] (1, 2) 2
[1 2] (2,) 1
------
[[[1]
  [2]
  [3]]] (1, 3, 1) 3
[[1]
 [2]
 [3]] (3, 1) 2
------
[1 2 3] (3,) 1


## 전치행렬(transpose)
- i,j값 switch

In [ ]:
arr = np.array([[1,2],[3,4]])

print(arr.T)

arr = np.array([[1,2,3],[3,4,5],[6,7,8]])

print(arr.T)

[[1 3]
 [2 4]]
[[1 3 6]
 [2 4 7]
 [3 5 8]]


In [ ]:
arr = np.array([[1,2,3],[3,4,5]])

print(arr.T)

[[1 3]
 [2 4]
 [3 5]]


In [ ]:
arr= np.array([[1,2],[3,4],[5,6]])
arr2 = np.full((3,2),2)

## dot - arr의 row 갯수와 arr2의 col갯수가 일치해야 곱셈이 됌
## 예시에서는 (3,2) (3,2)로 동일
#print(arr.dot(arr2))

## 전치행렬만들어주면 가능
arr= arr.T
print(arr.dot(arr2))

[[18 18]
 [24 24]]
