<a href="https://colab.research.google.com/github/kevin-hyun/numpy-practice/blob/main/6_%EB%B0%B0%EC%97%B4%EC%9D%98_%EB%B3%91%ED%95%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## 배열의 원소 추가 및 삭제

In [ ]:
# 1차원 배열 
arr = np.arange(1,9)
arr = np.insert(arr,2,50)
print(arr)


[ 1  2 50  3  4  5  6  7  8]


In [ ]:
# 2차원 배열

arr= np.arange(12).reshape(3,4)
print(arr)

## row- 2
arr = np.insert(arr,2,50,axis=1) 
print(arr)
## col -2 
arr = np.insert(arr,2,50,axis=1) 
print(arr)

## without axis -> 1 dim

arr= np.arange(12).reshape(3,4)
arr = np.insert(arr,2,50) 
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1 50  2  3]
 [ 4  5 50  6  7]
 [ 8  9 50 10 11]]
[[ 0  1 50 50  2  3]
 [ 4  5 50 50  6  7]
 [ 8  9 50 50 10 11]]
[ 0  1 50  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# delete 

arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.delete(arr,2,axis=0)
print(arr)

## without axis -> 1 dim

arr = np.arange(1,13).reshape(3,4)
arr = np.delete(arr,2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[ 1  2  4  5  6  7  8  9 10 11 12]


## 배열간의 병합

In [ ]:
# append - 배열 끝에 배열 추가 

arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

print(arr1)
print(arr2, end= "\n\n")

# axis = 0

arr3 = np.append(arr1,arr2,axis=0)
print(arr3,end='\n\n')

# axis = 1

arr3 = np.append(arr1,arr2,axis=1)
print(arr3,end='\n\n')


## without axis -> 1 dim
arr3 = np.append(arr1,arr2)
print(arr3,end='\n\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [ ]:
# vstack 

arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.vstack((arr1,arr2)) ## 괄호 2개!! 
print(arr3,end='\n\n')


# hstack

arr3 = np.hstack((arr1,arr2)) ## 괄호 2개!! 
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# concatanate()

# axis = 0 = vstack

arr3 = np.concatenate([arr1,arr2],axis=0)
print(arr3,end='\n\n')

# axis = 1 = hastack

arr3 = np.concatenate([arr1,arr2],axis=1)
print(arr3,end='\n\n')


## without axis -> axis=0
arr3 = np.concatenate([arr1,arr2])
print(arr3,end='\n\n')



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



# 배열 분할 


In [ ]:
# 2차원 배열 분할

arr = np.arange(1,13).reshape(3,4)
print(arr)

# vsplit - axis = 0 

## 1 -> 총 나뉜 개수가 1개 
arr_vsplit = np.vsplit(arr,1)
print(arr_vsplit[0])

## 3-> 총 나뉜 개수가 3개 
arr_vsplit = np.vsplit(arr,3)
print(arr_vsplit[0])

## 2-> 총 나뉜 개수가 2개  --> 에러 --> 행이 3개 -> 홀수만 가능  
# arr_vsplit = np.vsplit(arr,2)
# print(arr_vsplit[0])






[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[1]
 [5]
 [9]]


In [ ]:
# hsplit - axis = 1 

arr = np.arange(1,13).reshape(3,4)
print(arr,end="\n\n")

## 1 -> 총 나뉜 개수가 2개 
arr_hsplit = np.hsplit(arr,2)
print(arr_hsplit[0])

## 3-> 총 나뉜 개수가 4개 
arr_hsplit = np.hsplit(arr,4)
print(arr_hsplit[0])

## 3-> 총 나뉜 개수가 3개  --> 에러 --> 행이 3개 -> 홀수만 가능  
# arr_vsplit = np.vsplit(arr,3)
# print(arr_vsplit[0])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[1]
 [5]
 [9]]


In [ ]:
# 3차원 배열 

arr = np.random.randint(0,10,(4,6,8))
print(arr)

[[[6 2 6 9 8 1 3 2]
  [7 2 9 7 0 6 6 6]
  [3 1 1 3 9 9 7 0]
  [9 8 0 1 8 1 0 7]
  [5 2 1 1 0 1 3 3]
  [7 0 4 4 1 3 6 7]]

 [[5 5 6 2 0 8 3 9]
  [2 9 2 4 2 4 0 7]
  [6 3 6 6 9 9 7 3]
  [2 9 2 6 4 3 7 8]
  [3 8 9 7 1 0 1 4]
  [0 1 8 4 8 1 6 1]]

 [[2 1 1 5 3 1 6 8]
  [2 5 1 9 0 2 7 5]
  [1 4 2 2 0 2 7 0]
  [7 3 0 7 0 9 0 0]
  [3 5 4 4 5 0 8 3]
  [6 7 7 4 2 1 2 7]]

 [[3 1 5 2 0 5 7 6]
  [3 7 6 9 5 4 9 2]
  [5 9 5 3 4 3 5 8]
  [6 9 7 4 8 8 0 9]
  [5 3 5 2 4 2 8 2]
  [2 6 4 3 4 3 8 1]]]


In [ ]:
arr_vsplit= np.vsplit(arr,2)
print(arr_vsplit)

[array([[[6, 2, 6, 9, 8, 1, 3, 2],
        [7, 2, 9, 7, 0, 6, 6, 6],
        [3, 1, 1, 3, 9, 9, 7, 0],
        [9, 8, 0, 1, 8, 1, 0, 7],
        [5, 2, 1, 1, 0, 1, 3, 3],
        [7, 0, 4, 4, 1, 3, 6, 7]],

       [[5, 5, 6, 2, 0, 8, 3, 9],
        [2, 9, 2, 4, 2, 4, 0, 7],
        [6, 3, 6, 6, 9, 9, 7, 3],
        [2, 9, 2, 6, 4, 3, 7, 8],
        [3, 8, 9, 7, 1, 0, 1, 4],
        [0, 1, 8, 4, 8, 1, 6, 1]]]), array([[[2, 1, 1, 5, 3, 1, 6, 8],
        [2, 5, 1, 9, 0, 2, 7, 5],
        [1, 4, 2, 2, 0, 2, 7, 0],
        [7, 3, 0, 7, 0, 9, 0, 0],
        [3, 5, 4, 4, 5, 0, 8, 3],
        [6, 7, 7, 4, 2, 1, 2, 7]],

       [[3, 1, 5, 2, 0, 5, 7, 6],
        [3, 7, 6, 9, 5, 4, 9, 2],
        [5, 9, 5, 3, 4, 3, 5, 8],
        [6, 9, 7, 4, 8, 8, 0, 9],
        [5, 3, 5, 2, 4, 2, 8, 2],
        [2, 6, 4, 3, 4, 3, 8, 1]]])]


In [ ]:
arr_hsplit= np.hsplit(arr,2)
print(arr_hsplit)

[array([[[6, 2, 6, 9, 8, 1, 3, 2],
        [7, 2, 9, 7, 0, 6, 6, 6],
        [3, 1, 1, 3, 9, 9, 7, 0]],

       [[5, 5, 6, 2, 0, 8, 3, 9],
        [2, 9, 2, 4, 2, 4, 0, 7],
        [6, 3, 6, 6, 9, 9, 7, 3]],

       [[2, 1, 1, 5, 3, 1, 6, 8],
        [2, 5, 1, 9, 0, 2, 7, 5],
        [1, 4, 2, 2, 0, 2, 7, 0]],

       [[3, 1, 5, 2, 0, 5, 7, 6],
        [3, 7, 6, 9, 5, 4, 9, 2],
        [5, 9, 5, 3, 4, 3, 5, 8]]]), array([[[9, 8, 0, 1, 8, 1, 0, 7],
        [5, 2, 1, 1, 0, 1, 3, 3],
        [7, 0, 4, 4, 1, 3, 6, 7]],

       [[2, 9, 2, 6, 4, 3, 7, 8],
        [3, 8, 9, 7, 1, 0, 1, 4],
        [0, 1, 8, 4, 8, 1, 6, 1]],

       [[7, 3, 0, 7, 0, 9, 0, 0],
        [3, 5, 4, 4, 5, 0, 8, 3],
        [6, 7, 7, 4, 2, 1, 2, 7]],

       [[6, 9, 7, 4, 8, 8, 0, 9],
        [5, 3, 5, 2, 4, 2, 8, 2],
        [2, 6, 4, 3, 4, 3, 8, 1]]])]
