<a href="https://colab.research.google.com/github/kevin-hyun/numpy-practice/blob/main/7_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 예제1 
원소가 모두 3인 (3,4,5)형태의 numpy.array를 출력하시오 


In [ ]:
arr = np.full((3,4,5),3)
print(arr)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


# 예제2

정수 -50~ 50의 범위 안의 난수로 이루어진 (4,5) 형태의 numpy.array를 출력하고 행을 기준으로 오름차순 정렬한 결과와 전체 배열을 1차원 배열로 변경하여 오름차순 정렬한 결과를 출력하시오 


In [ ]:
arr = np.random.randint(-50,50,(4,5))
print(arr)
arr= np.sort(arr,axis=0)
print(arr)
arr= np.sort(arr,axis=None)
print(arr)





[[  0 -11 -30 -23  15]
 [-32 -18  -5 -22  18]
 [-32 -50   5 -28 -42]
 [-29  17  -7 -35   1]]
[[-32 -50 -30 -35 -42]
 [-32 -18  -7 -28   1]
 [-29 -11  -5 -23  15]
 [  0  17   5 -22  18]]
[-50 -42 -35 -32 -32 -30 -29 -28 -23 -22 -18 -11  -7  -5   0   1   5  15
  17  18]


# 예제3
다음과 같은 파이썬 list가 존재한다.
list 안에 있는 각 numpy.array의 원소들과 평균값과 표준편차 중앙값을 순서대로 구하여 구한 순서대로 원소가 이루어진 새로운 list를 구성하고 출력하시오 

평균값 3.0, 4.0, 5.0
표준편차 1.5, 1.7 1.9
중앙값 1.0 , 2.0 3.0 

배열 : [3.0, 1.5, 1.0 , 4.0, 1.7, 2.0, 5.0, 1.9, 3.0]

In [ ]:
py_list = [np.full(3,8),np.array([33,-15,26]),np.linspace(17,26,3)]
py_list = np.array(py_list)


arr_mean = np.mean(py_list,axis=1)
print(arr_mean)

arr_std = np.std(py_list,axis=1)
print(arr_std)


arr_median = np.median(py_list,axis=1)
print(arr_median)

print(np.append(arr_mean,arr_std))


## 배열 2개는 병합했는데 3개를 못함 ....


[ 8.         14.66666667 21.5       ]
[ 0.         21.17125934  3.67423461]
[ 8.  26.  21.5]
[ 8.         14.66666667 21.5         0.         21.17125934  3.67423461]


In [ ]:
## 답안 

## 반복문 사용 

result_arr = []
for i in py_list:
  result_arr.append(np.mean(i))
  result_arr.append(np.std(i))
  result_arr.append(np.median(i))

print(result_arr)


[8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0, 21.5, 3.6742346141747673, 21.5]


#예제4 
다음과 같은 numpy.array가 존재한다. 이 배열을 행을 기준으로 3개의 배열로 분할하여 분할된 각 배열의 원소들을 제곱한 결과를 다시 원본 배열에 행을 기준으로 병합하시오 
(단 마지막 출력결과는 원본 배열과 차원이 같아야 한다.) 



In [ ]:
arr = np.arange(2,20,2).reshape((3,3))
print(arr)

arr_vsplit = np.vsplit(arr,3)
print(arr_vsplit)
## 나누기까지 이해 ㅠㅠ 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]


In [ ]:
## 정답

arr = np.arange(2,20,2).reshape((3,3))
print(arr)

### 분할
s1 = np.vsplit(arr,3)
print(s1)

## 제곱

s2= np.square(s1)
print(s2)



## 3차원이 되어버림 -> 차원 일치 

s3= np.squeeze(s2, axis = 1) #y축 줄여야함 
print(s3)
## 병합

result_arr = np.vstack((arr,s3))
print(result_arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]
[[[  4  16  36]]

 [[ 64 100 144]]

 [[196 256 324]]]
[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]
[[  2   4   6]
 [  8  10  12]
 [ 14  16  18]
 [  4  16  36]
 [ 64 100 144]
 [196 256 324]]


#예제5

삼각함수의 특수각(0,30,60,90)을 numpy.array로 생성한 후 특수각에 해당하는 sin,cos,tan값을 각각 구하여 파이썬 list에 담은 해당list에 들어있는 값들을 출력하시오 
(단, 값이 무한대라면 "INF"문자열을 출력할 것)

numpy에서 삼각함수 radian 값을 사용하기 때문에 각을 radian으로 변경해야 합니다.

(degree * pi / 180)

In [4]:
import math
degree = np.array([0,30,60,90])
radian =[]
for i in degree:
  radian.append(i*np.pi/180)

result = []
for i in radian:
  if math.isinf(np.sin(i)):
    result.append("INF")
  else:
    result.append(np.sin(i))
  if math.isinf(np.cos(i)):
    result.append("INF")
  else:
    result.append(np.cos(i))
  if math.isinf(np.tan(i)):
    result.append("INF")
  else:
    result.append(np.tan(i)) 

print(result)


[0.0, 1.0, 0.0, 0.49999999999999994, 0.8660254037844387, 0.5773502691896257, 0.8660254037844386, 0.5000000000000001, 1.7320508075688767, 1.0, 6.123233995736766e-17, 1.633123935319537e+16]


In [8]:
## 정답 
### sin cos tan 각각 array -> 계산한 값을 2중 for 문 

arr = np.arange(0,91,30) ## 특수각 표현

lst =[]

lst.append(np.sin(arr*np.pi/180))
lst.append(np.cos(arr*np.pi/180))
lst.append(np.tan(arr*np.pi/180))

print(lst)
print()

for value_lst in lst:
  for value in value_lst:
    if value>99999999:
      print("INF")
      continue
    print(value)
  print()

[array([0.       , 0.5      , 0.8660254, 1.       ]), array([1.00000000e+00, 8.66025404e-01, 5.00000000e-01, 6.12323400e-17]), array([0.00000000e+00, 5.77350269e-01, 1.73205081e+00, 1.63312394e+16])]

0.0
0.49999999999999994
0.8660254037844386
1.0

1.0
0.8660254037844387
0.5000000000000001
6.123233995736766e-17

0.0
0.5773502691896257
1.7320508075688767
INF



# 예제 6 
numpy.array를 이용하여 다음과 같은 패턴을 출력하시오 (단 출력시 반복문을 사용하여 출력한다)


```
0101010
1010101
0101010
1010101
0101010
1010101

```

In [11]:
arr = np.full((6,6),0)

print(arr)


## 2차원 인덱싱 수정 못함 

print(arr)
arr2 = arr.ravel()
print(arr2)

for index,value in enumerate(arr2):
  if index!=0 & index%6==0:
    print(value,"\n")
  else:
    print(value,end="")

# ravel 이용해서 1차원으로 

arr2 = arr.ravel()


print(arr2)


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [22]:
## 정답

arr= np.zeros((7,7),dtype=int)


## 2칸 간격 1 -> 인덱싱

arr[::2,1::2] = 1
arr[1::2,0::2] =1


for row in range(7):
  for col in range(7):
    print(arr[row,col],end=" ")
  print()

0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
